### PR TITLE
Allow newer hspec

### PR DESCRIPTION
**Pull request by tfausak**
https://github.com/fpco/stackage/pull/2248

If you merge this, can you release a new version on Hackage? Thanks!

### CODE REVIEW

**Comment by tfausak** [comment]
Let me know if I can do anything to help move this pull request along, @ameingast!

**Comment by ameingast** [comment]
I'll try to get a release out by tomorrow.

Thanks for contributing!

**Comment by tfausak** [comment]
Great, thank you!

**Comment by ameingast** [comment]
Done and available at [hackage](https://hackage.haskell.org/package/postgresql-simple-migration-0.1.8.0).

**Pull request merged**
